
stages:
  - Build image
  -
docker build:
  stage: Build image
  image: docker:stable
  script:
    - docker login -u gitlab-ci-token -p $GITLAB_TOKEN registry.gitlab.com
    - docker info
    - docker build -t registry.gitlab.com/clouddrove/www .
    - docker push registry.gitlab.com/clouddrove/www
