image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $GITLAB_TOKEN registry.gitlab.com
    - docker info
    - docker build -t registry.gitlab.com/clouddrove/www .
    - docker push registry.gitlab.com/clouddrove/www
