image: docker:stable

stages:
  - Build image

docker build:
  stage: Build image
  script:
    - docker info
    - docker build -t registry.gitlab.com/clouddrove/www .

docker push:
  stage: Push to Docker Hub
  only:
    - master
  script:
    - docker push registry.gitlab.com/clouddrove/www


